### ISSUE TITLE
ScriptInjector 利用時の Ray.Di のビルトインモジュールの扱い

### ISSUE THREAD

**Issue by NaokiTsuchiya** [ray-di/Ray.Compiler#85]
`Ray.Di` はビルトインモジュールとして以下の3つのモジュールをインストールしています。 

* AssistedModule
* ProviderSetModule
* MultiBindingModule

ref: https://github.com/ray-di/Ray.Di/blob/2.x/src/di/ContainerFactory.php#L22-L26

上記のモジュールは `Ray\Di\Injector` を利用する場合には利用側が意識する必要はありませんが、`ScriptInjector` を利用する場合には利用側でモジュールをインストールする必要があります。

`ScriptInjector` を利用する際にも通常利用側が意識しないような作りが望ましいと感じましたがどうでしょうか。

**Comment by koriym** [comment]
必要ですね！
